#copy from https://gitee.com/hevey88/kitty/blob/main/kitty.conf
# font 
font_family     FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto 
# font_features FiraCode-Bold +zero +onum

font_size 12

# UI
tab_bar_edge top
cursor_shape block
#term xterm-256color
term xterm-kitty
#background_opacity 0.90
remember_window_size yes
hide_window_decorations yes
tab_bar_style powerline
#tab_powerline_style round
confirm_os_window_close 0

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9


# shell_integration enable
# tar_bar_style custom
tab_separator ""
tab_title_template "{index}"

map f1 show_kitty_env_vars
map f4 toggle_maximized

# 右键打开连接
mouse_map ctrl+left press ungrabbed,grabbed mouse_click_url
open_url_with default
copy_on_select yes
scrollback_lines 2000

allow_remote_control yes

include CatppuccinMocha.conf
#include tokyonight_storm.conf
#include tokyonight_night.conf
#include tokyonight_moon.conf
#include tokyonight_day.conf
# end copy gitee
